global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: metida
    metrics_path: /metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['127.0.0.1:8081']