{
 "title": "api dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(http_request_counters, instance)"
    }
   },
   {
    "name": "code",
    "label": "code",
    "query": {
     "query": "label_values(http_request_counters, code)"
    }
   },
   {
    "name": "method",
    "label": "method",
    "query": {
     "query": "label_values(http_request_counters, method)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(http_request_counters, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "http durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(path) (delta(http_request_durations_sum{instance=~\"$instance\", code=~\"$code\", method=~\"$method\", path=~\"$path\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round(sum by(code) (delta(http_request_counters{instance=~\"$instance\", code=~\"$code\", method=~\"$method\", path=~\"$path\"}[1m])), 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "db error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "idelta(db_error_counters[1m])", "legendFormat": "__auto" }
   ]
  }
 ]
}